// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcgen

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one

SELECT COUNT(*) FROM admin_user WHERE role = 'owner'
`

// Admin & Session Queries
// Purpose: admin user + server-side session read/write
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-17 23:18:17
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :execlastid
INSERT INTO admin_user (public_id, username, password_hash) VALUES (?, ?, ?)
`

type CreateAdminUserParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdminUser, arg.PublicID, arg.Username, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createSession = `-- name: CreateSession :exec
INSERT INTO session (token, admin_id, csrf_token, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string `db:"token" json:"token"`
	AdminID   int64  `db:"admin_id" json:"admin_id"`
	CsrfToken string `db:"csrf_token" json:"csrf_token"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.AdminID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByAdmin = `-- name: DeleteSessionsByAdmin :exec
DELETE FROM session WHERE admin_id = ?
`

func (q *Queries) DeleteSessionsByAdmin(ctx context.Context, adminID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByAdmin, adminID)
	return err
}

const ensureDemoUser = `-- name: EnsureDemoUser :exec
INSERT OR IGNORE INTO admin_user (public_id, username, password_hash, role) VALUES (?, ?, ?, 'demo')
`

type EnsureDemoUserParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) EnsureDemoUser(ctx context.Context, arg EnsureDemoUserParams) error {
	_, err := q.db.ExecContext(ctx, ensureDemoUser, arg.PublicID, arg.Username, arg.PasswordHash)
	return err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, public_id, username, password_hash, role FROM admin_user WHERE id = ?
`

type GetAdminUserByIDRow struct {
	ID           int64  `db:"id" json:"id"`
	PublicID     string `db:"public_id" json:"public_id"`
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
}

func (q *Queries) GetAdminUserByID(ctx context.Context, id int64) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByID, id)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, public_id, username, password_hash, role FROM admin_user WHERE username = ?
`

type GetAdminUserByUsernameRow struct {
	ID           int64  `db:"id" json:"id"`
	PublicID     string `db:"public_id" json:"public_id"`
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
}

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (GetAdminUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i GetAdminUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.token, s.admin_id, s.csrf_token, s.expires_at, a.username, a.public_id, a.role FROM session s JOIN admin_user a ON a.id = s.admin_id WHERE s.token = ? AND s.expires_at > ?
`

type GetSessionByTokenParams struct {
	Token     string `db:"token" json:"token"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

type GetSessionByTokenRow struct {
	Token     string `db:"token" json:"token"`
	AdminID   int64  `db:"admin_id" json:"admin_id"`
	CsrfToken string `db:"csrf_token" json:"csrf_token"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
	Username  string `db:"username" json:"username"`
	PublicID  string `db:"public_id" json:"public_id"`
	Role      string `db:"role" json:"role"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, arg.Token, arg.ExpiresAt)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.Token,
		&i.AdminID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.Username,
		&i.PublicID,
		&i.Role,
	)
	return i, err
}

const updateOwnerCredentials = `-- name: UpdateOwnerCredentials :execrows
UPDATE admin_user SET username = ?, password_hash = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? AND role = 'owner'
`

type UpdateOwnerCredentialsParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	ID           int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateOwnerCredentials(ctx context.Context, arg UpdateOwnerCredentialsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOwnerCredentials, arg.Username, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
