// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcgen

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec

INSERT INTO audit_event (public_id, admin_id, action, target_type, target_public_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	PublicID       string `db:"public_id" json:"public_id"`
	AdminID        int64  `db:"admin_id" json:"admin_id"`
	Action         string `db:"action" json:"action"`
	TargetType     string `db:"target_type" json:"target_type"`
	TargetPublicID string `db:"target_public_id" json:"target_public_id"`
}

// Audit Event Queries
// Purpose: append and list admin audit events
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-08-24 00:20:00
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.PublicID,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetPublicID,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT e.public_id, e.action, e.target_type, e.target_public_id, e.created_at,
       a.public_id AS admin_public_id, a.username AS admin_username
FROM audit_event e
JOIN admin_user a ON a.id = e.admin_id
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?
`

type ListAuditEventsRow struct {
	PublicID       string `db:"public_id" json:"public_id"`
	Action         string `db:"action" json:"action"`
	TargetType     string `db:"target_type" json:"target_type"`
	TargetPublicID string `db:"target_public_id" json:"target_public_id"`
	CreatedAt      string `db:"created_at" json:"created_at"`
	AdminPublicID  string `db:"admin_public_id" json:"admin_public_id"`
	AdminUsername  string `db:"admin_username" json:"admin_username"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, limit int64) ([]ListAuditEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Action,
			&i.TargetType,
			&i.TargetPublicID,
			&i.CreatedAt,
			&i.AdminPublicID,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
