// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addCartItem = `-- name: AddCartItem :exec
INSERT INTO cart_item (cart_id, variant_id, quantity) VALUES (?, ?, ?) ON CONFLICT(cart_id, variant_id) DO UPDATE SET quantity = quantity + excluded.quantity, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type AddCartItemParams struct {
	CartID    int64 `db:"cart_id" json:"cart_id"`
	VariantID int64 `db:"variant_id" json:"variant_id"`
	Quantity  int64 `db:"quantity" json:"quantity"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) error {
	_, err := q.db.ExecContext(ctx, addCartItem, arg.CartID, arg.VariantID, arg.Quantity)
	return err
}

const countCartItems = `-- name: CountCartItems :one
SELECT COALESCE(SUM(quantity), 0) FROM cart_item WHERE cart_id = ?
`

func (q *Queries) CountCartItems(ctx context.Context, cartID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, countCartItems, cartID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const createCart = `-- name: CreateCart :execlastid

INSERT INTO cart (token, status) VALUES (?, 'active')
`

// Cart Queries
// Purpose: anonymous cart + items read/write
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-18 12:40:00
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CreateCart(ctx context.Context, token string) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCart, token)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getActiveCartByToken = `-- name: GetActiveCartByToken :one
SELECT id, token, status FROM cart WHERE token = ? AND status = 'active'
`

type GetActiveCartByTokenRow struct {
	ID     int64  `db:"id" json:"id"`
	Token  string `db:"token" json:"token"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) GetActiveCartByToken(ctx context.Context, token string) (GetActiveCartByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartByToken, token)
	var i GetActiveCartByTokenRow
	err := row.Scan(&i.ID, &i.Token, &i.Status)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.variant_id, ci.quantity, v.public_id AS variant_public_id, v.sku, v.price_cents, p.id AS product_id, p.title AS product_title, p.slug AS product_slug, p.status AS product_status FROM cart_item ci JOIN variant v ON v.id = ci.variant_id JOIN product p ON p.id = v.product_id WHERE ci.cart_id = ? ORDER BY ci.id
`

type ListCartItemsRow struct {
	VariantID       int64          `db:"variant_id" json:"variant_id"`
	Quantity        int64          `db:"quantity" json:"quantity"`
	VariantPublicID string         `db:"variant_public_id" json:"variant_public_id"`
	Sku             sql.NullString `db:"sku" json:"sku"`
	PriceCents      int64          `db:"price_cents" json:"price_cents"`
	ProductID       int64          `db:"product_id" json:"product_id"`
	ProductTitle    string         `db:"product_title" json:"product_title"`
	ProductSlug     string         `db:"product_slug" json:"product_slug"`
	ProductStatus   string         `db:"product_status" json:"product_status"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsRow{}
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.VariantID,
			&i.Quantity,
			&i.VariantPublicID,
			&i.Sku,
			&i.PriceCents,
			&i.ProductID,
			&i.ProductTitle,
			&i.ProductSlug,
			&i.ProductStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsForVariant = `-- name: ListOptionsForVariant :many
SELECT po.name AS option_name, pov.value AS option_value, po.position AS option_position FROM variant_option_value vov JOIN product_option po ON po.id = vov.option_id JOIN product_option_value pov ON pov.id = vov.value_id WHERE vov.variant_id = ? ORDER BY po.position
`

type ListOptionsForVariantRow struct {
	OptionName     string `db:"option_name" json:"option_name"`
	OptionValue    string `db:"option_value" json:"option_value"`
	OptionPosition int64  `db:"option_position" json:"option_position"`
}

func (q *Queries) ListOptionsForVariant(ctx context.Context, variantID int64) ([]ListOptionsForVariantRow, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsForVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionsForVariantRow{}
	for rows.Next() {
		var i ListOptionsForVariantRow
		if err := rows.Scan(&i.OptionName, &i.OptionValue, &i.OptionPosition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_item WHERE cart_id = ? AND variant_id = ?
`

type RemoveCartItemParams struct {
	CartID    int64 `db:"cart_id" json:"cart_id"`
	VariantID int64 `db:"variant_id" json:"variant_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.ExecContext(ctx, removeCartItem, arg.CartID, arg.VariantID)
	return err
}

const setCartItemQty = `-- name: SetCartItemQty :exec
UPDATE cart_item SET quantity = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE cart_id = ? AND variant_id = ?
`

type SetCartItemQtyParams struct {
	Quantity  int64 `db:"quantity" json:"quantity"`
	CartID    int64 `db:"cart_id" json:"cart_id"`
	VariantID int64 `db:"variant_id" json:"variant_id"`
}

func (q *Queries) SetCartItemQty(ctx context.Context, arg SetCartItemQtyParams) error {
	_, err := q.db.ExecContext(ctx, setCartItemQty, arg.Quantity, arg.CartID, arg.VariantID)
	return err
}

const touchCart = `-- name: TouchCart :exec
UPDATE cart SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?
`

func (q *Queries) TouchCart(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchCart, id)
	return err
}
