// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :execlastid

INSERT INTO category (public_id, name, slug, parent_id, position) VALUES (?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	PublicID string        `db:"public_id" json:"public_id"`
	Name     string        `db:"name" json:"name"`
	Slug     string        `db:"slug" json:"slug"`
	ParentID sql.NullInt64 `db:"parent_id" json:"parent_id"`
	Position int64         `db:"position" json:"position"`
}

// Category Queries
// Purpose: category create, product-category link
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-17 18:13:43
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory,
		arg.PublicID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCategoryByPublicID = `-- name: GetCategoryByPublicID :one
SELECT id, public_id, name, slug, position FROM category WHERE public_id = ? AND deleted_at IS NULL
`

type GetCategoryByPublicIDRow struct {
	ID       int64  `db:"id" json:"id"`
	PublicID string `db:"public_id" json:"public_id"`
	Name     string `db:"name" json:"name"`
	Slug     string `db:"slug" json:"slug"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) GetCategoryByPublicID(ctx context.Context, publicID string) (GetCategoryByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByPublicID, publicID)
	var i GetCategoryByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Slug,
		&i.Position,
	)
	return i, err
}

const linkProductCategory = `-- name: LinkProductCategory :exec
INSERT OR IGNORE INTO product_category (product_id, category_id) VALUES (?, ?)
`

type LinkProductCategoryParams struct {
	ProductID  int64 `db:"product_id" json:"product_id"`
	CategoryID int64 `db:"category_id" json:"category_id"`
}

func (q *Queries) LinkProductCategory(ctx context.Context, arg LinkProductCategoryParams) error {
	_, err := q.db.ExecContext(ctx, linkProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, public_id, name, slug, position FROM category WHERE deleted_at IS NULL ORDER BY position, id
`

type ListCategoriesRow struct {
	ID       int64  `db:"id" json:"id"`
	PublicID string `db:"public_id" json:"public_id"`
	Name     string `db:"name" json:"name"`
	Slug     string `db:"slug" json:"slug"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Slug,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
