// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlcgen

import (
	"context"
)

const createContentPage = `-- name: CreateContentPage :execlastid

INSERT INTO content_page (public_id, title, slug, body_markdown, seo_description, status) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateContentPageParams struct {
	PublicID       string `db:"public_id" json:"public_id"`
	Title          string `db:"title" json:"title"`
	Slug           string `db:"slug" json:"slug"`
	BodyMarkdown   string `db:"body_markdown" json:"body_markdown"`
	SeoDescription string `db:"seo_description" json:"seo_description"`
	Status         string `db:"status" json:"status"`
}

// Content Page Queries
// Purpose: admin content page create, list, read, update, soft delete
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-09-07 12:00:00
func (q *Queries) CreateContentPage(ctx context.Context, arg CreateContentPageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createContentPage,
		arg.PublicID,
		arg.Title,
		arg.Slug,
		arg.BodyMarkdown,
		arg.SeoDescription,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getContentPageByPublicID = `-- name: GetContentPageByPublicID :one
SELECT id, public_id, title, slug, body_markdown, seo_description, status, created_at, updated_at FROM content_page WHERE public_id = ? AND deleted_at IS NULL
`

type GetContentPageByPublicIDRow struct {
	ID             int64  `db:"id" json:"id"`
	PublicID       string `db:"public_id" json:"public_id"`
	Title          string `db:"title" json:"title"`
	Slug           string `db:"slug" json:"slug"`
	BodyMarkdown   string `db:"body_markdown" json:"body_markdown"`
	SeoDescription string `db:"seo_description" json:"seo_description"`
	Status         string `db:"status" json:"status"`
	CreatedAt      string `db:"created_at" json:"created_at"`
	UpdatedAt      string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetContentPageByPublicID(ctx context.Context, publicID string) (GetContentPageByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContentPageByPublicID, publicID)
	var i GetContentPageByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.SeoDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentPages = `-- name: ListContentPages :many
SELECT id, public_id, title, slug, body_markdown, seo_description, status, created_at, updated_at FROM content_page WHERE deleted_at IS NULL ORDER BY updated_at DESC
`

type ListContentPagesRow struct {
	ID             int64  `db:"id" json:"id"`
	PublicID       string `db:"public_id" json:"public_id"`
	Title          string `db:"title" json:"title"`
	Slug           string `db:"slug" json:"slug"`
	BodyMarkdown   string `db:"body_markdown" json:"body_markdown"`
	SeoDescription string `db:"seo_description" json:"seo_description"`
	Status         string `db:"status" json:"status"`
	CreatedAt      string `db:"created_at" json:"created_at"`
	UpdatedAt      string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListContentPages(ctx context.Context) ([]ListContentPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listContentPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentPagesRow{}
	for rows.Next() {
		var i ListContentPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Slug,
			&i.BodyMarkdown,
			&i.SeoDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteContentPage = `-- name: SoftDeleteContentPage :exec
UPDATE content_page SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteContentPage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteContentPage, id)
	return err
}

const updateContentPage = `-- name: UpdateContentPage :exec
UPDATE content_page SET title = ?, body_markdown = ?, seo_description = ?, status = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? AND deleted_at IS NULL
`

type UpdateContentPageParams struct {
	Title          string `db:"title" json:"title"`
	BodyMarkdown   string `db:"body_markdown" json:"body_markdown"`
	SeoDescription string `db:"seo_description" json:"seo_description"`
	Status         string `db:"status" json:"status"`
	ID             int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateContentPage(ctx context.Context, arg UpdateContentPageParams) error {
	_, err := q.db.ExecContext(ctx, updateContentPage,
		arg.Title,
		arg.BodyMarkdown,
		arg.SeoDescription,
		arg.Status,
		arg.ID,
	)
	return err
}
