// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlcgen

import (
	"context"
)

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT COUNT(*) FROM product WHERE deleted_at IS NULL
`

// Products not soft-deleted.
func (q *Queries) CountActiveProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardOrderWindow = `-- name: DashboardOrderWindow :one

SELECT COUNT(*) AS order_count, CAST(COALESCE(SUM(CASE WHEN status IN ('paid', 'fulfilled') THEN total_cents ELSE 0 END), 0) AS INTEGER) AS sales_cents FROM "order" WHERE created_at >= ?
`

type DashboardOrderWindowRow struct {
	OrderCount int64 `db:"order_count" json:"order_count"`
	SalesCents int64 `db:"sales_cents" json:"sales_cents"`
}

// Dashboard Aggregate Queries
// Purpose: overview stats - order counts/sales by time window, pending fulfillment, product count, stock alerts
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-07-07 18:47:01
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md). All aggregation in SQL (no N+1).
// Orders created at/after a boundary: total count (any status) + sales sum counting paid/fulfilled only (D6). Refunded orders leave paid/fulfilled so are fully excluded. CAST keeps sqlc types as int64.
func (q *Queries) DashboardOrderWindow(ctx context.Context, createdAt string) (DashboardOrderWindowRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardOrderWindow, createdAt)
	var i DashboardOrderWindowRow
	err := row.Scan(&i.OrderCount, &i.SalesCents)
	return i, err
}

const dashboardPendingFulfillment = `-- name: DashboardPendingFulfillment :one
SELECT COUNT(*) FROM "order" WHERE status = 'paid'
`

// Backlog needing action: paid orders not yet fulfilled (D2). Not time-windowed.
func (q *Queries) DashboardPendingFulfillment(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardPendingFulfillment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardStockAlerts = `-- name: DashboardStockAlerts :one
SELECT CAST(COALESCE(SUM(CASE WHEN inv.quantity - inv.reserved <= 0 THEN 1 ELSE 0 END), 0) AS INTEGER) AS zero_stock, CAST(COALESCE(SUM(CASE WHEN inv.quantity - inv.reserved > 0 AND inv.quantity - inv.reserved <= 5 THEN 1 ELSE 0 END), 0) AS INTEGER) AS low_stock FROM inventory inv JOIN variant v ON v.id = inv.variant_id AND v.deleted_at IS NULL JOIN product p ON p.id = v.product_id AND p.deleted_at IS NULL
`

type DashboardStockAlertsRow struct {
	ZeroStock int64 `db:"zero_stock" json:"zero_stock"`
	LowStock  int64 `db:"low_stock" json:"low_stock"`
}

// Sellable = quantity - reserved; zero (<=0) and low (1..5) counts over non-deleted variants of non-deleted products (D3, N=5 fixed). CAST keeps sqlc types as int64.
func (q *Queries) DashboardStockAlerts(ctx context.Context) (DashboardStockAlertsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardStockAlerts)
	var i DashboardStockAlertsRow
	err := row.Scan(&i.ZeroStock, &i.LowStock)
	return i, err
}
