// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demo.sql

package sqlcgen

import (
	"context"
)

const canDemoViewProduct = `-- name: CanDemoViewProduct :one
SELECT EXISTS(
    SELECT 1 FROM product p
    WHERE p.public_id = ? AND p.deleted_at IS NULL
      AND (NOT EXISTS(SELECT 1 FROM demo_product any_demo WHERE any_demo.product_id = p.id)
           OR EXISTS(SELECT 1 FROM demo_product own WHERE own.product_id = p.id AND own.session_token = ?))
)
`

type CanDemoViewProductParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	SessionToken string `db:"session_token" json:"session_token"`
}

func (q *Queries) CanDemoViewProduct(ctx context.Context, arg CanDemoViewProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, canDemoViewProduct, arg.PublicID, arg.SessionToken)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const claimDemoProduct = `-- name: ClaimDemoProduct :exec
INSERT INTO demo_product (product_id, session_token, slot, expires_at) VALUES (?, ?, ?, ?)
`

type ClaimDemoProductParams struct {
	ProductID    int64  `db:"product_id" json:"product_id"`
	SessionToken string `db:"session_token" json:"session_token"`
	Slot         int64  `db:"slot" json:"slot"`
	ExpiresAt    string `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ClaimDemoProduct(ctx context.Context, arg ClaimDemoProductParams) error {
	_, err := q.db.ExecContext(ctx, claimDemoProduct,
		arg.ProductID,
		arg.SessionToken,
		arg.Slot,
		arg.ExpiresAt,
	)
	return err
}

const countDemoProductsBySession = `-- name: CountDemoProductsBySession :one

SELECT COUNT(*) FROM demo_product dp JOIN product p ON p.id = dp.product_id
WHERE dp.session_token = ? AND p.deleted_at IS NULL
`

// Public Demo Queries
// Purpose: temporary product ownership, quota checks, and expiry cleanup
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-09-13 11:00:00
func (q *Queries) CountDemoProductsBySession(ctx context.Context, sessionToken string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDemoProductsBySession, sessionToken)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDemoProductClaim = `-- name: DeleteDemoProductClaim :exec
DELETE FROM demo_product WHERE product_id = ?
`

func (q *Queries) DeleteDemoProductClaim(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDemoProductClaim, productID)
	return err
}

const hardDeleteProduct = `-- name: HardDeleteProduct :exec
DELETE FROM product WHERE id = ?
`

func (q *Queries) HardDeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteProduct, id)
	return err
}

const isDemoMediaOwnedBySession = `-- name: IsDemoMediaOwnedBySession :one
SELECT EXISTS(
    SELECT 1 FROM demo_product dp
    JOIN media_asset m ON m.product_id = dp.product_id
    WHERE m.public_id = ? AND dp.session_token = ? AND m.deleted_at IS NULL
)
`

type IsDemoMediaOwnedBySessionParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	SessionToken string `db:"session_token" json:"session_token"`
}

func (q *Queries) IsDemoMediaOwnedBySession(ctx context.Context, arg IsDemoMediaOwnedBySessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isDemoMediaOwnedBySession, arg.PublicID, arg.SessionToken)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isDemoProductOwnedBySession = `-- name: IsDemoProductOwnedBySession :one
SELECT EXISTS(
    SELECT 1 FROM demo_product dp JOIN product p ON p.id = dp.product_id
    WHERE p.public_id = ? AND dp.session_token = ? AND p.deleted_at IS NULL
)
`

type IsDemoProductOwnedBySessionParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	SessionToken string `db:"session_token" json:"session_token"`
}

func (q *Queries) IsDemoProductOwnedBySession(ctx context.Context, arg IsDemoProductOwnedBySessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isDemoProductOwnedBySession, arg.PublicID, arg.SessionToken)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isDemoVariantOwnedBySession = `-- name: IsDemoVariantOwnedBySession :one
SELECT EXISTS(
    SELECT 1 FROM demo_product dp
    JOIN product p ON p.id = dp.product_id
    JOIN variant v ON v.product_id = p.id
    WHERE v.public_id = ? AND dp.session_token = ? AND p.deleted_at IS NULL AND v.deleted_at IS NULL
)
`

type IsDemoVariantOwnedBySessionParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	SessionToken string `db:"session_token" json:"session_token"`
}

func (q *Queries) IsDemoVariantOwnedBySession(ctx context.Context, arg IsDemoVariantOwnedBySessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isDemoVariantOwnedBySession, arg.PublicID, arg.SessionToken)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDemoProductsBySession = `-- name: ListDemoProductsBySession :many
SELECT p.id, p.public_id FROM demo_product dp JOIN product p ON p.id = dp.product_id
WHERE dp.session_token = ? ORDER BY p.id
`

type ListDemoProductsBySessionRow struct {
	ID       int64  `db:"id" json:"id"`
	PublicID string `db:"public_id" json:"public_id"`
}

func (q *Queries) ListDemoProductsBySession(ctx context.Context, sessionToken string) ([]ListDemoProductsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listDemoProductsBySession, sessionToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDemoProductsBySessionRow{}
	for rows.Next() {
		var i ListDemoProductsBySessionRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDemoProducts = `-- name: ListExpiredDemoProducts :many
SELECT p.id, p.public_id FROM demo_product dp JOIN product p ON p.id = dp.product_id
WHERE dp.expires_at <= ? ORDER BY p.id
`

type ListExpiredDemoProductsRow struct {
	ID       int64  `db:"id" json:"id"`
	PublicID string `db:"public_id" json:"public_id"`
}

func (q *Queries) ListExpiredDemoProducts(ctx context.Context, expiresAt string) ([]ListExpiredDemoProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredDemoProducts, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredDemoProductsRow{}
	for rows.Next() {
		var i ListExpiredDemoProductsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsVisibleToDemo = `-- name: ListProductsVisibleToDemo :many
SELECT p.id, p.public_id, p.title, p.slug, p.status, p.featured, p.created_at, p.updated_at,
       EXISTS(SELECT 1 FROM demo_product own WHERE own.product_id = p.id AND own.session_token = ?) AS demo_owned
FROM product p
WHERE p.deleted_at IS NULL
  AND (NOT EXISTS(SELECT 1 FROM demo_product any_demo WHERE any_demo.product_id = p.id)
       OR EXISTS(SELECT 1 FROM demo_product own WHERE own.product_id = p.id AND own.session_token = ?))
ORDER BY p.id DESC
`

type ListProductsVisibleToDemoParams struct {
	SessionToken   string `db:"session_token" json:"session_token"`
	SessionToken_2 string `db:"session_token_2" json:"session_token_2"`
}

type ListProductsVisibleToDemoRow struct {
	ID        int64  `db:"id" json:"id"`
	PublicID  string `db:"public_id" json:"public_id"`
	Title     string `db:"title" json:"title"`
	Slug      string `db:"slug" json:"slug"`
	Status    string `db:"status" json:"status"`
	Featured  int64  `db:"featured" json:"featured"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	DemoOwned int64  `db:"demo_owned" json:"demo_owned"`
}

func (q *Queries) ListProductsVisibleToDemo(ctx context.Context, arg ListProductsVisibleToDemoParams) ([]ListProductsVisibleToDemoRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsVisibleToDemo, arg.SessionToken, arg.SessionToken_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsVisibleToDemoRow{}
	for rows.Next() {
		var i ListProductsVisibleToDemoRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.Featured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DemoOwned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
