// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlcgen

import (
	"context"
)

const getInventory = `-- name: GetInventory :one
SELECT variant_id, quantity, reserved, updated_at FROM inventory WHERE variant_id = ?
`

func (q *Queries) GetInventory(ctx context.Context, variantID int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, variantID)
	var i Inventory
	err := row.Scan(
		&i.VariantID,
		&i.Quantity,
		&i.Reserved,
		&i.UpdatedAt,
	)
	return i, err
}

const setInventory = `-- name: SetInventory :exec

INSERT INTO inventory (variant_id, quantity) VALUES (?, ?) ON CONFLICT(variant_id) DO UPDATE SET quantity = excluded.quantity, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type SetInventoryParams struct {
	VariantID int64 `db:"variant_id" json:"variant_id"`
	Quantity  int64 `db:"quantity" json:"quantity"`
}

// Inventory Queries
// Purpose: per-variant inventory set/read (reserved seeds M2 oversell guard)
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-17 18:13:43
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) SetInventory(ctx context.Context, arg SetInventoryParams) error {
	_, err := q.db.ExecContext(ctx, setInventory, arg.VariantID, arg.Quantity)
	return err
}
