// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlcgen

import (
	"context"
)

const addDerivative = `-- name: AddDerivative :exec
INSERT INTO media_derivative (asset_id, label, path, format, width, height, size_bytes) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddDerivativeParams struct {
	AssetID   int64  `db:"asset_id" json:"asset_id"`
	Label     string `db:"label" json:"label"`
	Path      string `db:"path" json:"path"`
	Format    string `db:"format" json:"format"`
	Width     int64  `db:"width" json:"width"`
	Height    int64  `db:"height" json:"height"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) AddDerivative(ctx context.Context, arg AddDerivativeParams) error {
	_, err := q.db.ExecContext(ctx, addDerivative,
		arg.AssetID,
		arg.Label,
		arg.Path,
		arg.Format,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
	)
	return err
}

const countMediaByProduct = `-- name: CountMediaByProduct :one
SELECT COUNT(*) FROM media_asset WHERE product_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountMediaByProduct(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaAsset = `-- name: CreateMediaAsset :execlastid

INSERT INTO media_asset (public_id, product_id, content_hash, original_path, mime, width, height, size_bytes, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMediaAssetParams struct {
	PublicID     string `db:"public_id" json:"public_id"`
	ProductID    int64  `db:"product_id" json:"product_id"`
	ContentHash  string `db:"content_hash" json:"content_hash"`
	OriginalPath string `db:"original_path" json:"original_path"`
	Mime         string `db:"mime" json:"mime"`
	Width        int64  `db:"width" json:"width"`
	Height       int64  `db:"height" json:"height"`
	SizeBytes    int64  `db:"size_bytes" json:"size_bytes"`
	Position     int64  `db:"position" json:"position"`
}

// Media Queries
// Purpose: media asset + derivative read/write, orphan cleanup
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-18 09:48:36
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMediaAsset,
		arg.PublicID,
		arg.ProductID,
		arg.ContentHash,
		arg.OriginalPath,
		arg.Mime,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getMediaByPublicID = `-- name: GetMediaByPublicID :one
SELECT id, public_id, product_id, content_hash, original_path FROM media_asset WHERE public_id = ? AND deleted_at IS NULL
`

type GetMediaByPublicIDRow struct {
	ID           int64  `db:"id" json:"id"`
	PublicID     string `db:"public_id" json:"public_id"`
	ProductID    int64  `db:"product_id" json:"product_id"`
	ContentHash  string `db:"content_hash" json:"content_hash"`
	OriginalPath string `db:"original_path" json:"original_path"`
}

func (q *Queries) GetMediaByPublicID(ctx context.Context, publicID string) (GetMediaByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaByPublicID, publicID)
	var i GetMediaByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProductID,
		&i.ContentHash,
		&i.OriginalPath,
	)
	return i, err
}

const hardDeleteMedia = `-- name: HardDeleteMedia :exec
DELETE FROM media_asset WHERE id = ?
`

func (q *Queries) HardDeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteMedia, id)
	return err
}

const listDerivativePathsByAsset = `-- name: ListDerivativePathsByAsset :many
SELECT path FROM media_derivative WHERE asset_id = ?
`

func (q *Queries) ListDerivativePathsByAsset(ctx context.Context, assetID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDerivativePathsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDerivativesByAsset = `-- name: ListDerivativesByAsset :many
SELECT label, path, format, width, height, size_bytes FROM media_derivative WHERE asset_id = ? ORDER BY width
`

type ListDerivativesByAssetRow struct {
	Label     string `db:"label" json:"label"`
	Path      string `db:"path" json:"path"`
	Format    string `db:"format" json:"format"`
	Width     int64  `db:"width" json:"width"`
	Height    int64  `db:"height" json:"height"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) ListDerivativesByAsset(ctx context.Context, assetID int64) ([]ListDerivativesByAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, listDerivativesByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDerivativesByAssetRow{}
	for rows.Next() {
		var i ListDerivativesByAssetRow
		if err := rows.Scan(
			&i.Label,
			&i.Path,
			&i.Format,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByProduct = `-- name: ListMediaByProduct :many
SELECT id, public_id, content_hash, original_path, mime, width, height, size_bytes, position FROM media_asset WHERE product_id = ? AND deleted_at IS NULL ORDER BY position, id
`

type ListMediaByProductRow struct {
	ID           int64  `db:"id" json:"id"`
	PublicID     string `db:"public_id" json:"public_id"`
	ContentHash  string `db:"content_hash" json:"content_hash"`
	OriginalPath string `db:"original_path" json:"original_path"`
	Mime         string `db:"mime" json:"mime"`
	Width        int64  `db:"width" json:"width"`
	Height       int64  `db:"height" json:"height"`
	SizeBytes    int64  `db:"size_bytes" json:"size_bytes"`
	Position     int64  `db:"position" json:"position"`
}

func (q *Queries) ListMediaByProduct(ctx context.Context, productID int64) ([]ListMediaByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaByProductRow{}
	for rows.Next() {
		var i ListMediaByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ContentHash,
			&i.OriginalPath,
			&i.Mime,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanMedia = `-- name: ListOrphanMedia :many
SELECT m.id, m.original_path FROM media_asset m JOIN product p ON p.id = m.product_id WHERE m.deleted_at IS NOT NULL OR p.deleted_at IS NOT NULL
`

type ListOrphanMediaRow struct {
	ID           int64  `db:"id" json:"id"`
	OriginalPath string `db:"original_path" json:"original_path"`
}

func (q *Queries) ListOrphanMedia(ctx context.Context) ([]ListOrphanMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanMediaRow{}
	for rows.Next() {
		var i ListOrphanMediaRow
		if err := rows.Scan(&i.ID, &i.OriginalPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media_asset SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteMedia, id)
	return err
}
