// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlcgen

import (
	"context"
)

const getMeta = `-- name: GetMeta :one
SELECT key, value, created_at, updated_at FROM meta WHERE key = ?
`

func (q *Queries) GetMeta(ctx context.Context, key string) (Meta, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var i Meta
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO meta (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertMetaParams struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}
