// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type AdminUser struct {
	ID           int64  `db:"id" json:"id"`
	PublicID     string `db:"public_id" json:"public_id"`
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	CreatedAt    string `db:"created_at" json:"created_at"`
	UpdatedAt    string `db:"updated_at" json:"updated_at"`
}

type Cart struct {
	ID        int64  `db:"id" json:"id"`
	Token     string `db:"token" json:"token"`
	Status    string `db:"status" json:"status"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type CartItem struct {
	ID        int64  `db:"id" json:"id"`
	CartID    int64  `db:"cart_id" json:"cart_id"`
	VariantID int64  `db:"variant_id" json:"variant_id"`
	Quantity  int64  `db:"quantity" json:"quantity"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Category struct {
	ID        int64          `db:"id" json:"id"`
	PublicID  string         `db:"public_id" json:"public_id"`
	Name      string         `db:"name" json:"name"`
	Slug      string         `db:"slug" json:"slug"`
	ParentID  sql.NullInt64  `db:"parent_id" json:"parent_id"`
	Position  int64          `db:"position" json:"position"`
	CreatedAt string         `db:"created_at" json:"created_at"`
	UpdatedAt string         `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullString `db:"deleted_at" json:"deleted_at"`
}

type Customer struct {
	ID        int64  `db:"id" json:"id"`
	PublicID  string `db:"public_id" json:"public_id"`
	Email     string `db:"email" json:"email"`
	Name      string `db:"name" json:"name"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Inventory struct {
	VariantID int64  `db:"variant_id" json:"variant_id"`
	Quantity  int64  `db:"quantity" json:"quantity"`
	Reserved  int64  `db:"reserved" json:"reserved"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type MediaAsset struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     string         `db:"public_id" json:"public_id"`
	ProductID    int64          `db:"product_id" json:"product_id"`
	ContentHash  string         `db:"content_hash" json:"content_hash"`
	OriginalPath string         `db:"original_path" json:"original_path"`
	Mime         string         `db:"mime" json:"mime"`
	Width        int64          `db:"width" json:"width"`
	Height       int64          `db:"height" json:"height"`
	SizeBytes    int64          `db:"size_bytes" json:"size_bytes"`
	Position     int64          `db:"position" json:"position"`
	CreatedAt    string         `db:"created_at" json:"created_at"`
	DeletedAt    sql.NullString `db:"deleted_at" json:"deleted_at"`
}

type MediaDerivative struct {
	ID        int64  `db:"id" json:"id"`
	AssetID   int64  `db:"asset_id" json:"asset_id"`
	Label     string `db:"label" json:"label"`
	Path      string `db:"path" json:"path"`
	Format    string `db:"format" json:"format"`
	Width     int64  `db:"width" json:"width"`
	Height    int64  `db:"height" json:"height"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

type Meta struct {
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID              int64  `db:"id" json:"id"`
	PublicID        string `db:"public_id" json:"public_id"`
	CustomerID      int64  `db:"customer_id" json:"customer_id"`
	Status          string `db:"status" json:"status"`
	Email           string `db:"email" json:"email"`
	ShipName        string `db:"ship_name" json:"ship_name"`
	ShipPhone       string `db:"ship_phone" json:"ship_phone"`
	ShipAddress     string `db:"ship_address" json:"ship_address"`
	ShipCountry     string `db:"ship_country" json:"ship_country"`
	Currency        string `db:"currency" json:"currency"`
	SubtotalCents   int64  `db:"subtotal_cents" json:"subtotal_cents"`
	TotalCents      int64  `db:"total_cents" json:"total_cents"`
	CreatedAt       string `db:"created_at" json:"created_at"`
	UpdatedAt       string `db:"updated_at" json:"updated_at"`
	PaymentProvider string `db:"payment_provider" json:"payment_provider"`
	PaymentRef      string `db:"payment_ref" json:"payment_ref"`
}

type OrderItem struct {
	ID           int64  `db:"id" json:"id"`
	OrderID      int64  `db:"order_id" json:"order_id"`
	VariantID    int64  `db:"variant_id" json:"variant_id"`
	ProductTitle string `db:"product_title" json:"product_title"`
	VariantLabel string `db:"variant_label" json:"variant_label"`
	Sku          string `db:"sku" json:"sku"`
	UnitCents    int64  `db:"unit_cents" json:"unit_cents"`
	Quantity     int64  `db:"quantity" json:"quantity"`
	LineCents    int64  `db:"line_cents" json:"line_cents"`
}

type Product struct {
	ID          int64          `db:"id" json:"id"`
	PublicID    string         `db:"public_id" json:"public_id"`
	Title       string         `db:"title" json:"title"`
	Slug        string         `db:"slug" json:"slug"`
	Description string         `db:"description" json:"description"`
	Status      string         `db:"status" json:"status"`
	CreatedAt   string         `db:"created_at" json:"created_at"`
	UpdatedAt   string         `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullString `db:"deleted_at" json:"deleted_at"`
}

type ProductCategory struct {
	ProductID  int64 `db:"product_id" json:"product_id"`
	CategoryID int64 `db:"category_id" json:"category_id"`
}

type ProductOption struct {
	ID        int64  `db:"id" json:"id"`
	ProductID int64  `db:"product_id" json:"product_id"`
	Name      string `db:"name" json:"name"`
	Position  int64  `db:"position" json:"position"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type ProductOptionValue struct {
	ID        int64  `db:"id" json:"id"`
	OptionID  int64  `db:"option_id" json:"option_id"`
	Value     string `db:"value" json:"value"`
	Position  int64  `db:"position" json:"position"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Refund struct {
	ID               int64  `db:"id" json:"id"`
	OrderID          int64  `db:"order_id" json:"order_id"`
	Provider         string `db:"provider" json:"provider"`
	ProviderRefundID string `db:"provider_refund_id" json:"provider_refund_id"`
	AmountCents      int64  `db:"amount_cents" json:"amount_cents"`
	CreatedAt        string `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        int64  `db:"id" json:"id"`
	Token     string `db:"token" json:"token"`
	AdminID   int64  `db:"admin_id" json:"admin_id"`
	CsrfToken string `db:"csrf_token" json:"csrf_token"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
	CreatedAt string `db:"created_at" json:"created_at"`
}

type Setting struct {
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
	Encrypted int64  `db:"encrypted" json:"encrypted"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Variant struct {
	ID         int64          `db:"id" json:"id"`
	PublicID   string         `db:"public_id" json:"public_id"`
	ProductID  int64          `db:"product_id" json:"product_id"`
	Sku        sql.NullString `db:"sku" json:"sku"`
	PriceCents int64          `db:"price_cents" json:"price_cents"`
	OptionKey  string         `db:"option_key" json:"option_key"`
	Position   int64          `db:"position" json:"position"`
	CreatedAt  string         `db:"created_at" json:"created_at"`
	UpdatedAt  string         `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullString `db:"deleted_at" json:"deleted_at"`
}

type VariantOptionValue struct {
	VariantID int64 `db:"variant_id" json:"variant_id"`
	OptionID  int64 `db:"option_id" json:"option_id"`
	ValueID   int64 `db:"value_id" json:"value_id"`
}

type WebhookEvent struct {
	ID         int64  `db:"id" json:"id"`
	Provider   string `db:"provider" json:"provider"`
	EventID    string `db:"event_id" json:"event_id"`
	EventType  string `db:"event_type" json:"event_type"`
	OrderRef   string `db:"order_ref" json:"order_ref"`
	ReceivedAt string `db:"received_at" json:"received_at"`
}
