// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlcgen

import (
	"context"
)

const createOrder = `-- name: CreateOrder :execlastid
INSERT INTO "order" (public_id, customer_id, status, email, ship_name, ship_phone, ship_address, ship_country, currency, subtotal_cents, total_cents) VALUES (?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	PublicID      string `db:"public_id" json:"public_id"`
	CustomerID    int64  `db:"customer_id" json:"customer_id"`
	Email         string `db:"email" json:"email"`
	ShipName      string `db:"ship_name" json:"ship_name"`
	ShipPhone     string `db:"ship_phone" json:"ship_phone"`
	ShipAddress   string `db:"ship_address" json:"ship_address"`
	ShipCountry   string `db:"ship_country" json:"ship_country"`
	Currency      string `db:"currency" json:"currency"`
	SubtotalCents int64  `db:"subtotal_cents" json:"subtotal_cents"`
	TotalCents    int64  `db:"total_cents" json:"total_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrder,
		arg.PublicID,
		arg.CustomerID,
		arg.Email,
		arg.ShipName,
		arg.ShipPhone,
		arg.ShipAddress,
		arg.ShipCountry,
		arg.Currency,
		arg.SubtotalCents,
		arg.TotalCents,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_item (order_id, variant_id, product_title, variant_label, sku, unit_cents, quantity, line_cents) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID      int64  `db:"order_id" json:"order_id"`
	VariantID    int64  `db:"variant_id" json:"variant_id"`
	ProductTitle string `db:"product_title" json:"product_title"`
	VariantLabel string `db:"variant_label" json:"variant_label"`
	Sku          string `db:"sku" json:"sku"`
	UnitCents    int64  `db:"unit_cents" json:"unit_cents"`
	Quantity     int64  `db:"quantity" json:"quantity"`
	LineCents    int64  `db:"line_cents" json:"line_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.ProductTitle,
		arg.VariantLabel,
		arg.Sku,
		arg.UnitCents,
		arg.Quantity,
		arg.LineCents,
	)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, public_id, email, name FROM customer WHERE email = ?
`

type GetCustomerByEmailRow struct {
	ID       int64  `db:"id" json:"id"`
	PublicID string `db:"public_id" json:"public_id"`
	Email    string `db:"email" json:"email"`
	Name     string `db:"name" json:"name"`
}

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (GetCustomerByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i GetCustomerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getOrderByPublicID = `-- name: GetOrderByPublicID :one
SELECT id, public_id, status, email, ship_name, ship_phone, ship_address, ship_country, currency, subtotal_cents, total_cents, payment_provider, payment_ref, created_at FROM "order" WHERE public_id = ?
`

type GetOrderByPublicIDRow struct {
	ID              int64  `db:"id" json:"id"`
	PublicID        string `db:"public_id" json:"public_id"`
	Status          string `db:"status" json:"status"`
	Email           string `db:"email" json:"email"`
	ShipName        string `db:"ship_name" json:"ship_name"`
	ShipPhone       string `db:"ship_phone" json:"ship_phone"`
	ShipAddress     string `db:"ship_address" json:"ship_address"`
	ShipCountry     string `db:"ship_country" json:"ship_country"`
	Currency        string `db:"currency" json:"currency"`
	SubtotalCents   int64  `db:"subtotal_cents" json:"subtotal_cents"`
	TotalCents      int64  `db:"total_cents" json:"total_cents"`
	PaymentProvider string `db:"payment_provider" json:"payment_provider"`
	PaymentRef      string `db:"payment_ref" json:"payment_ref"`
	CreatedAt       string `db:"created_at" json:"created_at"`
}

func (q *Queries) GetOrderByPublicID(ctx context.Context, publicID string) (GetOrderByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByPublicID, publicID)
	var i GetOrderByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Status,
		&i.Email,
		&i.ShipName,
		&i.ShipPhone,
		&i.ShipAddress,
		&i.ShipCountry,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.PaymentProvider,
		&i.PaymentRef,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT product_title, variant_label, sku, unit_cents, quantity, line_cents FROM order_item WHERE order_id = ? ORDER BY id
`

type ListOrderItemsRow struct {
	ProductTitle string `db:"product_title" json:"product_title"`
	VariantLabel string `db:"variant_label" json:"variant_label"`
	Sku          string `db:"sku" json:"sku"`
	UnitCents    int64  `db:"unit_cents" json:"unit_cents"`
	Quantity     int64  `db:"quantity" json:"quantity"`
	LineCents    int64  `db:"line_cents" json:"line_cents"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ProductTitle,
			&i.VariantLabel,
			&i.Sku,
			&i.UnitCents,
			&i.Quantity,
			&i.LineCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForAdmin = `-- name: ListOrdersForAdmin :many
SELECT id, public_id, status, email, currency, total_cents, payment_provider, created_at FROM "order" ORDER BY id DESC
`

type ListOrdersForAdminRow struct {
	ID              int64  `db:"id" json:"id"`
	PublicID        string `db:"public_id" json:"public_id"`
	Status          string `db:"status" json:"status"`
	Email           string `db:"email" json:"email"`
	Currency        string `db:"currency" json:"currency"`
	TotalCents      int64  `db:"total_cents" json:"total_cents"`
	PaymentProvider string `db:"payment_provider" json:"payment_provider"`
	CreatedAt       string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListOrdersForAdmin(ctx context.Context) ([]ListOrdersForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersForAdminRow{}
	for rows.Next() {
		var i ListOrdersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Status,
			&i.Email,
			&i.Currency,
			&i.TotalCents,
			&i.PaymentProvider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsByOrder = `-- name: ListRefundsByOrder :many
SELECT provider, provider_refund_id, amount_cents, created_at FROM refund WHERE order_id = ? ORDER BY id
`

type ListRefundsByOrderRow struct {
	Provider         string `db:"provider" json:"provider"`
	ProviderRefundID string `db:"provider_refund_id" json:"provider_refund_id"`
	AmountCents      int64  `db:"amount_cents" json:"amount_cents"`
	CreatedAt        string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListRefundsByOrder(ctx context.Context, orderID int64) ([]ListRefundsByOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, listRefundsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefundsByOrderRow{}
	for rows.Next() {
		var i ListRefundsByOrderRow
		if err := rows.Scan(
			&i.Provider,
			&i.ProviderRefundID,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCartConverted = `-- name: MarkCartConverted :exec
UPDATE cart SET status = 'converted', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?
`

func (q *Queries) MarkCartConverted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCartConverted, id)
	return err
}

const reserveInventory = `-- name: ReserveInventory :execrows
UPDATE inventory SET reserved = reserved + ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE variant_id = ? AND quantity - reserved >= ?
`

type ReserveInventoryParams struct {
	Reserved  int64 `db:"reserved" json:"reserved"`
	VariantID int64 `db:"variant_id" json:"variant_id"`
	Quantity  int64 `db:"quantity" json:"quantity"`
}

func (q *Queries) ReserveInventory(ctx context.Context, arg ReserveInventoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveInventory, arg.Reserved, arg.VariantID, arg.Quantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCustomer = `-- name: UpsertCustomer :exec

INSERT INTO customer (public_id, email, name) VALUES (?, ?, ?) ON CONFLICT(email) DO UPDATE SET name = excluded.name, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertCustomerParams struct {
	PublicID string `db:"public_id" json:"public_id"`
	Email    string `db:"email" json:"email"`
	Name     string `db:"name" json:"name"`
}

// Order & Checkout Queries
// Purpose: customer upsert, order/order_item create, atomic inventory reserve, order read
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-18 13:40:31
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) error {
	_, err := q.db.ExecContext(ctx, upsertCustomer, arg.PublicID, arg.Email, arg.Name)
	return err
}
