// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const claimDueEmails = `-- name: ClaimDueEmails :many
SELECT id, order_id, to_addr, subject, body, attempts FROM email_outbox WHERE status = 'pending' AND next_attempt_at <= ? ORDER BY id LIMIT ?
`

type ClaimDueEmailsParams struct {
	NextAttemptAt string `db:"next_attempt_at" json:"next_attempt_at"`
	Limit         int64  `db:"limit" json:"limit"`
}

type ClaimDueEmailsRow struct {
	ID       int64  `db:"id" json:"id"`
	OrderID  int64  `db:"order_id" json:"order_id"`
	ToAddr   string `db:"to_addr" json:"to_addr"`
	Subject  string `db:"subject" json:"subject"`
	Body     string `db:"body" json:"body"`
	Attempts int64  `db:"attempts" json:"attempts"`
}

// Due pending emails (next_attempt_at reached), oldest first, limited batch. Worker sends outside any tx.
func (q *Queries) ClaimDueEmails(ctx context.Context, arg ClaimDueEmailsParams) ([]ClaimDueEmailsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimDueEmails, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueEmailsRow{}
	for rows.Next() {
		var i ClaimDueEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ToAddr,
			&i.Subject,
			&i.Body,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueEmail = `-- name: EnqueueEmail :execrows

INSERT OR IGNORE INTO email_outbox (order_id, kind, to_addr, subject, body) VALUES (?, ?, ?, ?, ?)
`

type EnqueueEmailParams struct {
	OrderID int64  `db:"order_id" json:"order_id"`
	Kind    string `db:"kind" json:"kind"`
	ToAddr  string `db:"to_addr" json:"to_addr"`
	Subject string `db:"subject" json:"subject"`
	Body    string `db:"body" json:"body"`
}

// Email Outbox Queries
// Purpose: enqueue (idempotent), claim due, mark sending/sent/failed/skipped, boot recovery
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-07-28 13:27:02
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
// Idempotent: UNIQUE(order_id,kind) makes a duplicate enqueue a no-op (PayPal sync capture + webhook backup).
func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueEmail,
		arg.OrderID,
		arg.Kind,
		arg.ToAddr,
		arg.Subject,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE email_outbox SET status = 'failed', attempts = ?, last_error = ? WHERE id = ?
`

type MarkEmailFailedParams struct {
	Attempts  int64  `db:"attempts" json:"attempts"`
	LastError string `db:"last_error" json:"last_error"`
	ID        int64  `db:"id" json:"id"`
}

// Send failed and attempts exhausted: dead-letter.
func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailFailed, arg.Attempts, arg.LastError, arg.ID)
	return err
}

const markEmailRetry = `-- name: MarkEmailRetry :exec
UPDATE email_outbox SET status = 'pending', attempts = ?, next_attempt_at = ?, last_error = ? WHERE id = ?
`

type MarkEmailRetryParams struct {
	Attempts      int64  `db:"attempts" json:"attempts"`
	NextAttemptAt string `db:"next_attempt_at" json:"next_attempt_at"`
	LastError     string `db:"last_error" json:"last_error"`
	ID            int64  `db:"id" json:"id"`
}

// Send failed but attempts left: back to pending with backoff + bumped attempts + last error.
func (q *Queries) MarkEmailRetry(ctx context.Context, arg MarkEmailRetryParams) error {
	_, err := q.db.ExecContext(ctx, markEmailRetry,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const markEmailSending = `-- name: MarkEmailSending :execrows
UPDATE email_outbox SET status = 'sending' WHERE id = ? AND status = 'pending'
`

// Claim one row pending->sending (rows=1 confirms claim). Quick single-statement; no network I/O held.
func (q *Queries) MarkEmailSending(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailSending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE email_outbox SET status = 'sent', sent_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'), last_error = '' WHERE id = ?
`

func (q *Queries) MarkEmailSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailSent, id)
	return err
}

const markEmailSkipped = `-- name: MarkEmailSkipped :exec
UPDATE email_outbox SET status = 'skipped', last_error = ? WHERE id = ?
`

type MarkEmailSkippedParams struct {
	LastError string `db:"last_error" json:"last_error"`
	ID        int64  `db:"id" json:"id"`
}

// SMTP not configured: skip (no retry, no backfill on later config).
func (q *Queries) MarkEmailSkipped(ctx context.Context, arg MarkEmailSkippedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailSkipped, arg.LastError, arg.ID)
	return err
}

const resetStaleSending = `-- name: ResetStaleSending :exec
UPDATE email_outbox SET status = 'pending' WHERE status = 'sending'
`

// Boot recovery: any row stuck in 'sending' (crash mid-send) back to pending for re-attempt.
func (q *Queries) ResetStaleSending(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetStaleSending)
	return err
}
