// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlcgen

import (
	"context"
)

const insertWebhookEvent = `-- name: InsertWebhookEvent :exec

INSERT INTO webhook_event (provider, event_id, event_type, order_ref) VALUES (?, ?, ?, ?)
`

type InsertWebhookEventParams struct {
	Provider  string `db:"provider" json:"provider"`
	EventID   string `db:"event_id" json:"event_id"`
	EventType string `db:"event_type" json:"event_type"`
	OrderRef  string `db:"order_ref" json:"order_ref"`
}

// Payment Queries
// Purpose: webhook idempotency (dedup insert) and order pending->paid transition
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-20 20:26:08
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, insertWebhookEvent,
		arg.Provider,
		arg.EventID,
		arg.EventType,
		arg.OrderRef,
	)
	return err
}

const markOrderPaidByPublicID = `-- name: MarkOrderPaidByPublicID :execrows
UPDATE "order" SET status = 'paid', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE public_id = ? AND status = 'pending'
`

func (q *Queries) MarkOrderPaidByPublicID(ctx context.Context, publicID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderPaidByPublicID, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
