// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value, encrypted FROM setting WHERE key = ?
`

type GetSettingRow struct {
	Value     string `db:"value" json:"value"`
	Encrypted int64  `db:"encrypted" json:"encrypted"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (GetSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Value, &i.Encrypted)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec

INSERT INTO setting (key, value, encrypted) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value, encrypted = excluded.encrypted, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertSettingParams struct {
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
	Encrypted int64  `db:"encrypted" json:"encrypted"`
}

// Settings Queries
// Purpose: key-value settings (plain or KEK-encrypted)
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-19 21:22:05
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.Encrypted)
	return err
}
