// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value, encrypted FROM setting WHERE key = ?
`

type GetSettingRow struct {
	Value     string `db:"value" json:"value"`
	Encrypted int64  `db:"encrypted" json:"encrypted"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (GetSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Value, &i.Encrypted)
	return i, err
}

const listEncryptedSettings = `-- name: ListEncryptedSettings :many
SELECT key, value FROM setting WHERE encrypted = 1 ORDER BY key
`

type ListEncryptedSettingsRow struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) ListEncryptedSettings(ctx context.Context) ([]ListEncryptedSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEncryptedSettingsRow{}
	for rows.Next() {
		var i ListEncryptedSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncryptedSettingValue = `-- name: UpdateEncryptedSettingValue :execrows
UPDATE setting SET value = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE key = ? AND encrypted = 1
`

type UpdateEncryptedSettingValueParams struct {
	Value string `db:"value" json:"value"`
	Key   string `db:"key" json:"key"`
}

func (q *Queries) UpdateEncryptedSettingValue(ctx context.Context, arg UpdateEncryptedSettingValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEncryptedSettingValue, arg.Value, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSetting = `-- name: UpsertSetting :exec

INSERT INTO setting (key, value, encrypted) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value, encrypted = excluded.encrypted, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertSettingParams struct {
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
	Encrypted int64  `db:"encrypted" json:"encrypted"`
}

// Settings Queries
// Purpose: key-value settings (plain or KEK-encrypted)
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-19 21:22:05
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.Encrypted)
	return err
}
