// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storefront.sql

package sqlcgen

import (
	"context"
)

const getActiveProductBySlug = `-- name: GetActiveProductBySlug :one
SELECT id, public_id, title, slug, description, updated_at FROM product WHERE slug = ? AND status = 'active' AND deleted_at IS NULL
`

type GetActiveProductBySlugRow struct {
	ID          int64  `db:"id" json:"id"`
	PublicID    string `db:"public_id" json:"public_id"`
	Title       string `db:"title" json:"title"`
	Slug        string `db:"slug" json:"slug"`
	Description string `db:"description" json:"description"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetActiveProductBySlug(ctx context.Context, slug string) (GetActiveProductBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveProductBySlug, slug)
	var i GetActiveProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many

SELECT id, public_id, title, slug, description, updated_at FROM product WHERE status = 'active' AND deleted_at IS NULL ORDER BY id DESC
`

type ListActiveProductsRow struct {
	ID          int64  `db:"id" json:"id"`
	PublicID    string `db:"public_id" json:"public_id"`
	Title       string `db:"title" json:"title"`
	Slug        string `db:"slug" json:"slug"`
	Description string `db:"description" json:"description"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

// Storefront Queries
// Purpose: public storefront reads (active products only)
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-18 11:20:00
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) ListActiveProducts(ctx context.Context) ([]ListActiveProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
