// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variant.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addVariantOptionValue = `-- name: AddVariantOptionValue :exec
INSERT INTO variant_option_value (variant_id, option_id, value_id) VALUES (?, ?, ?)
`

type AddVariantOptionValueParams struct {
	VariantID int64 `db:"variant_id" json:"variant_id"`
	OptionID  int64 `db:"option_id" json:"option_id"`
	ValueID   int64 `db:"value_id" json:"value_id"`
}

func (q *Queries) AddVariantOptionValue(ctx context.Context, arg AddVariantOptionValueParams) error {
	_, err := q.db.ExecContext(ctx, addVariantOptionValue, arg.VariantID, arg.OptionID, arg.ValueID)
	return err
}

const createVariant = `-- name: CreateVariant :execlastid

INSERT INTO variant (public_id, product_id, sku, price_cents, option_key, position) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateVariantParams struct {
	PublicID   string         `db:"public_id" json:"public_id"`
	ProductID  int64          `db:"product_id" json:"product_id"`
	Sku        sql.NullString `db:"sku" json:"sku"`
	PriceCents int64          `db:"price_cents" json:"price_cents"`
	OptionKey  string         `db:"option_key" json:"option_key"`
	Position   int64          `db:"position" json:"position"`
}

// Variant Queries
// Purpose: variant create/update, option-value links, variant matrix
// Author: daxing  Email: 3442535897@qq.com  Time: 2026-06-17 18:13:43
// NOTE: ASCII-only comments here (sqlc v1.30 multibyte-span bug; see DECISIONS.md).
func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVariant,
		arg.PublicID,
		arg.ProductID,
		arg.Sku,
		arg.PriceCents,
		arg.OptionKey,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listVariantOptionValuesByProduct = `-- name: ListVariantOptionValuesByProduct :many
SELECT v.id AS variant_id, po.name AS option_name, pov.value AS option_value, po.position AS option_position FROM variant v JOIN variant_option_value vov ON vov.variant_id = v.id JOIN product_option po ON po.id = vov.option_id JOIN product_option_value pov ON pov.id = vov.value_id WHERE v.product_id = ? AND v.deleted_at IS NULL ORDER BY v.position, v.id, po.position
`

type ListVariantOptionValuesByProductRow struct {
	VariantID      int64  `db:"variant_id" json:"variant_id"`
	OptionName     string `db:"option_name" json:"option_name"`
	OptionValue    string `db:"option_value" json:"option_value"`
	OptionPosition int64  `db:"option_position" json:"option_position"`
}

func (q *Queries) ListVariantOptionValuesByProduct(ctx context.Context, productID int64) ([]ListVariantOptionValuesByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantOptionValuesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantOptionValuesByProductRow{}
	for rows.Next() {
		var i ListVariantOptionValuesByProductRow
		if err := rows.Scan(
			&i.VariantID,
			&i.OptionName,
			&i.OptionValue,
			&i.OptionPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, public_id, sku, price_cents, option_key, position FROM variant WHERE product_id = ? AND deleted_at IS NULL ORDER BY position, id
`

type ListVariantsByProductRow struct {
	ID         int64          `db:"id" json:"id"`
	PublicID   string         `db:"public_id" json:"public_id"`
	Sku        sql.NullString `db:"sku" json:"sku"`
	PriceCents int64          `db:"price_cents" json:"price_cents"`
	OptionKey  string         `db:"option_key" json:"option_key"`
	Position   int64          `db:"position" json:"position"`
}

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID int64) ([]ListVariantsByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByProductRow{}
	for rows.Next() {
		var i ListVariantsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Sku,
			&i.PriceCents,
			&i.OptionKey,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
